version: '3.8'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: document-management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  auth-user-service:
    build: ./services/auth-user-service
    ports:
      - "3000:3000"
    env_file:
      - ./services/auth-user-service/.env
    depends_on:
      - rabbitmq
      - postgres

  ingestion-service:
    build: ./services/ingestion-service
    ports:
      - "3001:3001"
    env_file:
      - ./services/ingestion-service/.env
    depends_on:
      - rabbitmq
      - postgres

volumes:
  pgdata: